In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df =pd.read_csv("C:\\Users\\akelo\\Desktop\\DATASETS\\course_lead_scoring.csv")

In [3]:
df.head()

lead_source    industry  number_of_courses_viewed  annual_income  \
0      paid_ads         NaN                         1        79450.0   
1  social_media      retail                         1        46992.0   
2        events  healthcare                         5        78796.0   
3      paid_ads      retail                         2        83843.0   
4      referral   education                         3        85012.0   

  employment_status       location  interaction_count  lead_score  converted  
0        unemployed  south_america                  4        0.94          1  
1          employed  south_america                  1        0.80          0  
2        unemployed      australia                  3        0.69          1  
3               NaN      australia                  1        0.87          0  
4     self_employed         europe                  3        0.62          1

In [4]:
df.columns = df.columns.str.strip().str.replace(' ','_',regex = True).str.lower()
categorical_columns = list(df.dtypes[df.dtypes == 'object'].index)
for c in categorical_columns:
    df[c] = df[c].str.lower().str.strip().str.replace(' ','_',regex = True)
                    

In [5]:
df.dtypes

lead_source                  object
industry                     object
number_of_courses_viewed      int64
annual_income               float64
employment_status            object
location                     object
interaction_count             int64
lead_score                  float64
converted                     int64
dtype: object

In [6]:
df.columns

Index(['lead_source', 'industry', 'number_of_courses_viewed', 'annual_income',
       'employment_status', 'location', 'interaction_count', 'lead_score',
       'converted'],
      dtype='object')

In [7]:
categorical = [  'lead_source', 'industry',
       'employment_status', 'location']

In [8]:
numerical =['number_of_courses_viewed', 'annual_income',
       'interaction_count', 'lead_score','converted']

In [9]:
df.isnull().sum()

lead_source                 128
industry                    134
number_of_courses_viewed      0
annual_income               181
employment_status           100
location                     63
interaction_count             0
lead_score                    0
converted                     0
dtype: int64

In [10]:
df[[ 'lead_source', 'industry', 'employment_status', 'location']] = df [['lead_source', 'industry','employment_status', 'location']].astype('object')

In [11]:
df.dtypes

lead_source                  object
industry                     object
number_of_courses_viewed      int64
annual_income               float64
employment_status            object
location                     object
interaction_count             int64
lead_score                  float64
converted                     int64
dtype: object

In [12]:
df[[ 'lead_source', 'industry', 'employment_status', 'location']].isnull().sum()

lead_source          128
industry             134
employment_status    100
location              63
dtype: int64

In [13]:
df[df.select_dtypes(include = 'object').columns] = df.select_dtypes(include = 'object').fillna('NA')

In [14]:
df.select_dtypes(include = 'object').isnull().sum()

lead_source          0
industry             0
employment_status    0
location             0
dtype: int64

In [15]:
df[df.select_dtypes(include = ['int64','float64']).columns] = df.select_dtypes(include = ['float64','int64']).fillna(0)

In [16]:
df.select_dtypes(include = ['int64','float64']).isnull().sum()

number_of_courses_viewed    0
annual_income               0
interaction_count           0
lead_score                  0
converted                   0
dtype: int64

In [17]:
df['industry'].mode()

0    retail
Name: industry, dtype: object

In [18]:
#creating a correlation matrix for my numerical features
#But firstly we have to split our dataset
numerical

['number_of_courses_viewed',
 'annual_income',
 'interaction_count',
 'lead_score',
 'converted']

In [19]:
df[numerical]

number_of_courses_viewed  annual_income  interaction_count  lead_score  \
0                            1        79450.0                  4        0.94   
1                            1        46992.0                  1        0.80   
2                            5        78796.0                  3        0.69   
3                            2        83843.0                  1        0.87   
4                            3        85012.0                  3        0.62   
...                        ...            ...                ...         ...   
1457                         1            0.0                  4        0.53   
1458                         3        65259.0                  2        0.24   
1459                         1        45688.0                  3        0.02   
1460                         5        71016.0                  0        0.25   
1461                         3        92855.0                  3        0.41   

      converted  
0             1  
1             0  
2             1  
3             0  
4             1  
...         ...  
1457          1  
1458          1  
1459          1  
1460          1  
1461          1  

[1462 rows x 5 columns]

In [20]:
df.converted.head()

0    1
1    0
2    1
3    0
4    1
Name: converted, dtype: int64

In [21]:
from sklearn.model_selection import train_test_split                              

In [22]:
df_full_train,df_test = train_test_split(df,test_size =0.2,random_state = 1)

In [23]:
df_train,df_val = train_test_split(df_full_train,test_size =0.25,random_state = 1)

In [24]:
len(df_train),len(df_val),len(df_test)

(876, 293, 293)

In [25]:
len(df)

1462

In [26]:
y_full_train = df_full_train.converted.values
y_train =df_train.converted.values
y_val = df_val.converted.values
y_test = df_test.converted.values

In [27]:
idx = np.arange(len(df))

In [28]:
np.random.seed(42)
np.random.shuffle(idx)

In [29]:
df_full_train = df_full_train.reset_index(drop = True)
df_train =df_train.reset_index(drop = True)
df_test = df_test.reset_index(drop = True)
df_val =df_val.reset_index(drop = True)

In [30]:
df_train

lead_source       industry  number_of_courses_viewed  annual_income  \
0            events  manufacturing                         2        95543.0   
1          referral             NA                         1        54924.0   
2    organic_search     healthcare                         2        77352.0   
3          paid_ads          other                         2        34600.0   
4          paid_ads      education                         0        43615.0   
..              ...            ...                       ...            ...   
871              NA          other                         5        67314.0   
872          events      education                         6        63996.0   
873  organic_search        finance                         1        73702.0   
874          events     technology                         1        93341.0   
875    social_media        finance                         0            0.0   

    employment_status       location  interaction_count  lead_score  converted  
0          unemployed         europe                  3        0.78          0  
1             student  south_america                  6        0.39          1  
2          unemployed         europe                  2        0.22          0  
3            employed  south_america                  2        0.31          0  
4          unemployed  south_america                  2        0.01          0  
..                ...            ...                ...         ...        ...  
871                NA         europe                  2        0.87          1  
872                NA      australia                  4        0.92          1  
873        unemployed  north_america                  2        0.55          0  
874           student    middle_east                  4        0.99          0  
875        unemployed         africa                  3        0.73          0  

[876 rows x 9 columns]

In [31]:
df_val

lead_source       industry  number_of_courses_viewed  annual_income  \
0    organic_search  manufacturing                         1            0.0   
1          referral      education                         2        58777.0   
2          paid_ads     technology                         3        78148.0   
3      social_media     technology                         3        63854.0   
4          referral      education                         1        69099.0   
..              ...            ...                       ...            ...   
288        paid_ads        finance                         2        41947.0   
289        paid_ads          other                         2            0.0   
290        referral             NA                         4        92215.0   
291          events          other                         2        53087.0   
292          events     healthcare                         3        60375.0   

    employment_status       location  interaction_count  lead_score  converted  
0                  NA           asia                  0        0.73          1  
1                  NA  north_america                  0        0.94          1  
2            employed    middle_east                  2        0.80          1  
3            employed         africa                  1        0.10          0  
4          unemployed         africa                  4        0.98          1  
..                ...            ...                ...         ...        ...  
288     self_employed         europe                  4        0.10          1  
289     self_employed  north_america                  3        0.71          1  
290          employed      australia                  4        0.57          1  
291          employed         europe                  2        0.52          0  
292           student      australia                  9        0.30          1  

[293 rows x 9 columns]

In [32]:
df_test

lead_source    industry  number_of_courses_viewed  annual_income  \
0    organic_search  technology                         1            0.0   
1          paid_ads     finance                         1        47129.0   
2                NA   education                         0            0.0   
3            events      retail                         0        64775.0   
4      social_media     finance                         3        46934.0   
..              ...         ...                       ...            ...   
288          events       other                         3        80326.0   
289        referral   education                         0        77641.0   
290          events  technology                         1        70889.0   
291              NA       other                         2        57246.0   
292        referral  healthcare                         1            0.0   

    employment_status       location  interaction_count  lead_score  converted  
0            employed    middle_east                  2        0.90          0  
1                  NA  south_america                  1        0.93          0  
2          unemployed           asia                  5        0.97          1  
3       self_employed  south_america                  3        0.70          1  
4                  NA      australia                  3        0.26          1  
..                ...            ...                ...         ...        ...  
288     self_employed         africa                  6        0.27          1  
289           student         europe                  1        0.60          1  
290          employed           asia                  4        0.61          1  
291     self_employed           asia                  1        0.27          1  
292                NA           asia                  4        0.50          1  

[293 rows x 9 columns]

In [33]:
#del df_full_train['converted']
#del df_train['converted']
#del df_val['converted']
#del df_test['converted']

In [34]:
df_full_train.converted.value_counts(normalize = True)

converted
1    0.611634
0    0.388366
Name: proportion, dtype: float64

In [35]:
global_converted_rate = df_full_train.converted.mean()
global_converted_rate

np.float64(0.611633875106929)

In [36]:
df_full_train[numerical].corrwith(df_full_train.converted).abs()

number_of_courses_viewed    0.434872
annual_income               0.068845
interaction_count           0.387251
lead_score                  0.196394
converted                   1.000000
dtype: float64

In [37]:
#now i get working with mutual information score
from sklearn.metrics import mutual_info_score

In [40]:
def mutual_info_converted_score(series):
    return mutual_info_score(series,df_full_train.converted)
mi = df_full_train[categorical].apply(mutual_info_converted_score)
mi.sort_values(ascending = False)

lead_source          0.024562
employment_status    0.012690
industry             0.008173
location             0.001212
dtype: float64

In [ ]:
#now we want to train a logistic regression
#but first we need to perform the one hot encoding on the categorical data 

In [41]:
from sklearn.feature_extraction import DictVectorizer

In [43]:
train_dicts = df_train[categorical + numerical].to_dict(orient ='records')
dv =DictVectorizer(sparse = False)
dv.fit(train_dicts)


In [47]:
dv.transform(train_dicts)


array([[9.5543e+04, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        2.0000e+00],
       [5.4924e+04, 1.0000e+00, 0.0000e+00, ..., 0.0000e+00, 1.0000e+00,
        1.0000e+00],
       [7.7352e+04, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        2.0000e+00],
       ...,
       [7.3702e+04, 0.0000e+00, 0.0000e+00, ..., 1.0000e+00, 0.0000e+00,
        1.0000e+00],
       [9.3341e+04, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        1.0000e+00],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00]], shape=(876, 32))

In [48]:
x_train =dv.transform(train_dicts)

In [49]:
x_train.shape

(876, 32)

In [50]:
val_dicts =df_val[categorical + numerical].to_dict(orient = 'records')
x_val =dv.transform(val_dicts)

In [51]:
x_val

array([[0.0000e+00, 1.0000e+00, 1.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        1.0000e+00],
       [5.8777e+04, 1.0000e+00, 1.0000e+00, ..., 1.0000e+00, 0.0000e+00,
        2.0000e+00],
       [7.8148e+04, 1.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        3.0000e+00],
       ...,
       [9.2215e+04, 1.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        4.0000e+00],
       [5.3087e+04, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        2.0000e+00],
       [6.0375e+04, 1.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        3.0000e+00]], shape=(293, 32))

In [52]:
from sklearn.linear_model import LogisticRegression

In [54]:
model =LogisticRegression(solver = 'liblinear',C = 1.0,max_iter = 1000,random_state = 42)
model.fit(x_train,y_train)

LogisticRegression(max_iter=1000, random_state=42, solver='liblinear')

In [55]:
model.coef_

array([[-2.24417042e-05,  4.16288636e-01, -1.69893694e-02,
         2.74830579e-02, -1.26904559e-03,  1.67814508e-02,
        -7.09143854e-02, -1.04844847e-02,  2.55653621e-02,
        -3.52331099e-03, -1.21947744e-02, -5.33403569e-04,
        -1.73109807e-02, -1.56743994e-02, -1.07523002e-02,
         3.57114666e-01,  3.16051820e-02,  2.82689922e-03,
         1.38421723e-03, -1.01340182e-02, -7.01193236e-02,
         5.08914585e-02, -1.97575249e-02,  4.44352589e-03,
        -4.78042804e-03, -3.43639323e-03, -1.63514087e-02,
        -5.94627109e-03, -8.20788603e-03, -1.03704360e-02,
        -2.58994460e-04,  4.10655599e-01]])

In [57]:
model.coef_[0].round(3)

array([-0.   ,  0.416, -0.017,  0.027, -0.001,  0.017, -0.071, -0.01 ,
        0.026, -0.004, -0.012, -0.001, -0.017, -0.016, -0.011,  0.357,
        0.032,  0.003,  0.001, -0.01 , -0.07 ,  0.051, -0.02 ,  0.004,
       -0.005, -0.003, -0.016, -0.006, -0.008, -0.01 , -0.   ,  0.411])

In [58]:
model.intercept_[0]

np.float64(-0.044908291723174114)

In [59]:
model.predict_proba(x_train)

array([[0.58607395, 0.41392605],
       [0.14661618, 0.85338382],
       [0.58358671, 0.41641329],
       ...,
       [0.65736668, 0.34263332],
       [0.5671004 , 0.4328996 ],
       [0.27877788, 0.72122212]], shape=(876, 2))

In [60]:
#we want to apply the model to the validation dataset

In [63]:
y_pred = model.predict_proba(x_val)[:,1]
y_pred

array([0.68438868, 0.48811259, 0.62889747, 0.52660832, 0.66630728,
       0.74026167, 0.84750176, 0.32336091, 0.60411812, 0.91506643,
       0.80189204, 0.62476968, 0.92075802, 0.32052423, 0.89536029,
       0.90927215, 0.70208654, 0.53552104, 0.71264273, 0.74010546,
       0.81746473, 0.50007709, 0.90754628, 0.79878615, 0.93210808,
       0.62357556, 0.4869509 , 0.82448396, 0.50021335, 0.58906746,
       0.56642921, 0.52258226, 0.49125168, 0.9391268 , 0.68783968,
       0.68139446, 0.87309326, 0.83390482, 0.41318868, 0.74253517,
       0.84622803, 0.43113991, 0.41332327, 0.61191521, 0.69080728,
       0.74735837, 0.49473714, 0.71236347, 0.82596588, 0.8593041 ,
       0.83326901, 0.79272259, 0.80864348, 0.69602961, 0.79245428,
       0.72102328, 0.69415737, 0.5209775 , 0.68277362, 0.78249093,
       0.31427869, 0.74880745, 0.30894318, 0.7674952 , 0.45945937,
       0.18998348, 0.72394426, 0.40748751, 0.44513323, 0.60690764,
       0.89007406, 0.31432206, 0.42198201, 0.87572694, 0.73220

In [66]:
convert_decision =y_pred > 0.5
convert_decision

array([ True, False,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True, False,  True,  True, False, False,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True, False,
        True, False, False,  True, False, False,  True,  True, False,
       False,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
       False,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True, False,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True, False,

In [67]:
#now these are the people who are likely to convert with value more than 0.5
df_val[convert_decision]

lead_source       industry  number_of_courses_viewed  annual_income  \
0    organic_search  manufacturing                         1            0.0   
2          paid_ads     technology                         3        78148.0   
3      social_media     technology                         3        63854.0   
4          referral      education                         1        69099.0   
5    organic_search     technology                         1        51441.0   
..              ...            ...                       ...            ...   
288        paid_ads        finance                         2        41947.0   
289        paid_ads          other                         2            0.0   
290        referral             NA                         4        92215.0   
291          events          other                         2        53087.0   
292          events     healthcare                         3        60375.0   

    employment_status       location  interaction_count  lead_score  converted  
0                  NA           asia                  0        0.73          1  
2            employed    middle_east                  2        0.80          1  
3            employed         africa                  1        0.10          0  
4          unemployed         africa                  4        0.98          1  
5                  NA  south_america                  4        0.93          1  
..                ...            ...                ...         ...        ...  
288     self_employed         europe                  4        0.10          1  
289     self_employed  north_america                  3        0.71          1  
290          employed      australia                  4        0.57          1  
291          employed         europe                  2        0.52          0  
292           student      australia                  9        0.30          1  

[232 rows x 9 columns]

In [68]:
#now let us calculate the accuraccy
convert_decision.astype(int)

array([1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1])

In [70]:
(y_val == convert_decision).mean().round(2)

np.float64(0.77)

In [77]:
df_pred = pd.DataFrame()
df_pred ['probability'] =y_pred
df_pred['Prediction'] =convert_decision.astype(int)

df_pred

probability  Prediction
0       0.684389           1
1       0.488113           0
2       0.628897           1
3       0.526608           1
4       0.666307           1
..           ...         ...
288     0.832310           1
289     0.899113           1
290     0.808850           1
291     0.579645           1
292     0.969574           1

[293 rows x 2 columns]